version: "3.8"
services:
  app:
    build:
      context: ./app
    environment:
      - BGCOLOR=#FF0000
      - FGCOLOR=#FFF
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=app
    depends_on:
      - db

  proxy:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/auth.httpasswd:/etc/nginx/auth.httpasswd
    depends_on:
      - app

  db:
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5

volumes:
  db_data: